/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BinaryInput: typeof import('./src/components/BinaryInput.vue')['default']
    BipolarAMI: typeof import('./src/components/Block/BipolarAMI.vue')['default']
    Button: typeof import('primevue/button')['default']
    DiffManchester: typeof import('./src/components/Block/DiffManchester.vue')['default']
    Digit: typeof import('./src/components/Digit.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    Fill: typeof import('./src/components/Fill.vue')['default']
    FreqBlock: typeof import('./src/components/FreqBlock.vue')['default']
    Frequency: typeof import('./src/components/Frequency.vue')['default']
    Hotkey: typeof import('./src/components/Hotkey.vue')['default']
    LengthSlider: typeof import('./src/components/LengthSlider.vue')['default']
    Manchester: typeof import('./src/components/Block/Manchester.vue')['default']
    NrzI: typeof import('./src/components/Block/NrzI.vue')['default']
    NrzL: typeof import('./src/components/Block/NrzL.vue')['default']
    PseudoTernary: typeof import('./src/components/Block/PseudoTernary.vue')['default']
    Screen: typeof import('./src/components/Screen.vue')['default']
    Slider: typeof import('primevue/slider')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
